"""empty message

Revision ID: f9da6b1c64a2
Revises: f6f622dd21fd
Create Date: 2024-02-18 23:01:30.933298

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9da6b1c64a2'
down_revision = 'f6f622dd21fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.alter_column('nums_of_lines_allowed',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.alter_column('nums_of_lines_allowed',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
